# Generated by Django 4.0.1 on 2023-05-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=355)),
                ('manzil', models.CharField(max_length=355)),
                ('talablar', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('namuna_cv', models.FileField(upload_to='example_cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('yoshi', models.IntegerField()),
                ('staj', models.CharField(max_length=255)),
                ('ishchi_haqida', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('ish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiApp.ishlar')),
            ],
        ),
    ]
