# Generated by Django 4.0.1 on 2023-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0003_new_rename_ism_familiya_rahbarlar_uz_ism_familiya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
