# Generated by Django 4.0.1 on 2023-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0005_remove_ariza_cv_remove_ishlar_namuna_cv_ishlar_maosh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rahbarlar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='rahbarlar/'),
        ),
    ]
