# Generated by Django 4.0.1 on 2023-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0008_ishlar_mudat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hududlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='hududlar/')),
                ('manzil', models.CharField(max_length=255)),
                ('aholi', models.BigIntegerField(default=0)),
                ('maydoni', models.CharField(max_length=255)),
                ('loyhalar_soni', models.IntegerField(default=0)),
                ('ish_joyi_soni', models.BigIntegerField(default=0)),
            ],
        ),
    ]
