# Generated by Django 4.0.1 on 2023-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0010_baholashmezon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baholash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=555)),
                ('oquv_ishlari', models.IntegerField()),
                ('yoshlar', models.IntegerField()),
                ('ishlab_chiqarish', models.IntegerField()),
                ('moliyaviy', models.IntegerField()),
                ('xojalik', models.IntegerField()),
                ('talim_sifati', models.IntegerField()),
                ('ijro_intizomi', models.IntegerField()),
                ('jazo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
